const User = require('../models/User');

// Seed email addresses for all users
exports.seedUserEmails = async (req, res) => {
  try {
    console.log('🌱 Seeding user email addresses...');
    
    // Sample email addresses for different users
    const userEmailMappings = [
      // Admin users
      { name: /admin/i, email: 'admin@astu.edu.et', notificationEmail: 'admin@astu.edu.et' },
      { name: /system/i, email: 'system@astu.edu.et', notificationEmail: 'system@astu.edu.et' },
      
      // Researcher examples - you can customize these
      { name: /abraham/i, email: 'abraham.gebre@astu.edu.et', notificationEmail: 'abrahamgebreyohannes12@gmail.com' },
      { name: /dr\.\s*abraham/i, email: 'abraham.gebre@astu.edu.et', notificationEmail: 'abrahamgebreyohannes12@gmail.com' },
      { name: /gebre/i, email: 'abraham.gebre@astu.edu.et', notificationEmail: 'abrahamgebreyohannes12@gmail.com' },
    ];
    
    let updatedCount = 0;
    let createdEmailCount = 0;
    
    // Get all users
    const allUsers = await User.find({});
    console.log(`Found ${allUsers.length} users in database`);
    
    for (const user of allUsers) {
      console.log(`Processing user: ${user.name} (email: ${user.email || 'none'}, notificationEmail: ${user.notificationEmail || 'none'})`);
      let updated = false;
      
      // Try to match with predefined mappings
      for (const mapping of userEmailMappings) {
        if (mapping.name.test(user.name)) {
          // Update email if not set or different
          if (!user.email || user.email === '') {
            user.email = mapping.email;
            updated = true;
          }
          // Update notificationEmail if not set
          if (!user.notificationEmail || user.notificationEmail === '') {
            user.notificationEmail = mapping.notificationEmail;
            updated = true;
          } else if (user.notificationEmail !== mapping.notificationEmail && user.email === mapping.email) {
            // If email matches, update notificationEmail too
            user.notificationEmail = mapping.notificationEmail;
            updated = true;
          }
          break;
        }
      }
      
      // If no mapping found, ensure notificationEmail is set
      if (!user.notificationEmail || user.notificationEmail === '') {
        // Generate email from name: "John Doe" -> "john.doe@astu.edu.et"
        const emailPrefix = user.name.toLowerCase()
          .replace(/dr\.|prof\.|mr\.|mrs\.|ms\./gi, '') // Remove titles
          .trim()
          .replace(/\s+/g, '.') // Replace spaces with dots
          .replace(/[^a-z0-9.]/g, ''); // Remove special characters
        
        const genEmail = `${emailPrefix}@astu.edu.et`;
        
        // If email is default, update it
        if (!user.email || user.email === '' || user.email === 'your-email@gmail.com' || user.email.includes('your-email')) {
          user.email = genEmail;
          updated = true;
          createdEmailCount++;
        }
        
        // Always set notificationEmail
        user.notificationEmail = genEmail;
        updated = true;
      }
      
      if (updated) {
        await user.save();
        updatedCount++;
        console.log(`✅ Updated: ${user.name} -> ${user.email} (notifications: ${user.notificationEmail})`);
      }
    }
    
    console.log(`✅ Seeding complete! Updated ${updatedCount} users (${createdEmailCount} auto-generated emails)`);
    
    res.json({
      success: true,
      message: `Email addresses seeded successfully`,
      stats: {
        totalUsers: allUsers.length,
        updated: updatedCount,
        autoGenerated: createdEmailCount
      }
    });
  } catch (error) {
    console.error('❌ Error seeding emails:', error.message);
    res.status(500).json({ 
      success: false, 
      error: 'Failed to seed emails', 
      details: error.message 
    });
  }
};

// Update individual user email
exports.updateUserEmail = async (req, res) => {
  try {
    const { userId } = req.params;
    const { email, notificationEmail } = req.body;
    
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ success: false, error: 'User not found' });
    }
    
    if (email) user.email = email;
    if (notificationEmail) user.notificationEmail = notificationEmail;
    
    await user.save();
    
    res.json({
      success: true,
      message: 'User email updated',
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        notificationEmail: user.notificationEmail
      }
    });
  } catch (error) {
    console.error('❌ Error updating user email:', error.message);
    res.status(500).json({ 
      success: false, 
      error: 'Failed to update email', 
      details: error.message 
    });
  }
};

// Get all users with emails
exports.getAllUsersWithEmails = async (req, res) => {
  try {
    const users = await User.find({}, 'name email notificationEmail role college');
    
    res.json({
      success: true,
      count: users.length,
      users
    });
  } catch (error) {
    console.error('❌ Error fetching users:', error.message);
    res.status(500).json({ 
      success: false, 
      error: 'Failed to fetch users', 
      details: error.message 
    });
  }
};
